### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by syptic** [sos-nandita/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Missing example with keystroke count  
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by sos-nandita** [comment]
I have a question about this:
 We should run the example from part 7 and count our keystrokes and put that on the lab report?

**Comment by sos-nandita** [comment]
> Here is your feedback for Lab Report 1:
> 
> * [x]  All relevant URLs written as markdown links
> * [x]  All relevant code examples written with backticks (```)
> * [x]  All screenshots correspond to the described steps
> * [x]  All titles of sections are formatted as headers or similar
> * [x]  Lab report is on its own page, not the index page
> * [ ]  Last example counts keystrokes and shows how to run remotely saving time
>   
>   * Missing example with keystroke count
> * [x]  Text is formatted in a way that was easy for grader to read
> 
> Additional comments from your grader: Great job!
> 
> If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:
> 
> * Link to this issue
> * Link to your published lab report page
> 
> ```
> 
> ```

I have a question about this:
We should run the example from part 7 and count our keystrokes and put that on the lab report?

**Comment by syptic** [comment]
You can take any example you want.

**Comment by sos-nandita** [comment]
In my lab report, I wrote that the number of keystrokes was 2 (one for the up arrow key and one for enter key). Is this sufficient to get credit?
