### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by JIzabal** [sos-nandita/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
  - The expected output doesn't match the output shown in the test code
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
Great work so far! Besides the issue mentioned above, remember that expected output is the first argument to `assertEquals` and the actual output is the second argument to `assertEquals`.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by sos-nandita** [comment]
Sorry, I don't fully understand what "The expected output doesn't match the output shown in the test code" means. Can you please elaborate?

**Comment by JIzabal** [comment]
No worries! In `testGetLinksSnip1`, your `expectedoutput` is ```[`google.com, google.com, ucsd.edu]``` based on the code seen [here](https://github.com/sos-nandita/markdown-parse/blob/ab0f93652587dc542ff4f8c54f4f10a4906fb16a/MarkdownParseTest.java#L60-L63), but in the [Peer Output](https://github.com/sos-nandita/cse15l-lab-reports/blob/759bc4cac6fe40228b587a6aebac0c69ce287c48/lab-report-4-week-8.md?plain=1#L73-L75) section the expected output is shown as ```[`google.com]```. Fix this issue in your [picture](https://github.com/sos-nandita/cse15l-lab-reports/blob/main/lab4%20p1%20review.png), and once that's done submit a regrade request. Feel free to ask me any other questions you have!
